version: "3"

services:
  app: 
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/app
    networks:
      - work_app

  web:   
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./src/:/app
    networks:
      - work_app

  db:  
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3308:3306
    env_file:
        - ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - work_app
      
volumes:
  mysql-volume:

networks:
  work_app:
    driver: bridge